In [1]:
print("I love QF206!\n" * 3)

I love QF206!
I love QF206!
I love QF206!



# Variable

In [2]:
a = 1
a

1

In [3]:
print = 1
print(2)

TypeError: ignored

Q: any other reversed keyword in Python?

# Data types

In [5]:
a = 1
type(a)

int

In [6]:
b = 1.2
type(b)

float

Q: what happens if two variables of different data types are evaluated together?

In [7]:
c = True
type(c)

bool

In [8]:
d = "hi"
type(d)

str

In [9]:
e = [1, 2, 3]
type(e)

list

Q: any other way to build a list?

In [10]:
[i+1 for i in e]

[2, 3, 4]

Q: write the same operation in a for loop.

In [11]:
f = {"Mon":1, "Tue":2}
type(f)

dict

Q: build a dictionary of your group members.

## String

In [12]:
a = "Hi"
a[0]

'H'

In [13]:
b = "How are you"
b[:3]

'How'

In [14]:
a.upper()

'HI'

Q: explore three other methods of a string.

In [15]:
len(a)

2

In [16]:
"How" in b

True

Q: what happens if it is lower case, i.e., "how"? How to make it case insensitive?

In [17]:
a + " " + b

'Hi How are you'

## List

In [18]:
a = ["how", "are", "you"]

In [19]:
len(a)

3

In [20]:
a[2]

'you'

Q: how to access the last element without knowing the exact position?

In [21]:
a[0:2]

['how', 'are']

In [22]:
"are" in a

True

In [23]:
["hi"] + a

['hi', 'how', 'are', 'you']

Q: how to join these single words to a sentence?

## Dictionary

In [24]:
a = {"Mon":1, "Tue":2}

In [25]:
a["Mon"]

1

In [26]:
a["Wed"] = 3
a

{'Mon': 1, 'Tue': 2, 'Wed': 3}

In [27]:
a["Mon"] = 0
a

{'Mon': 0, 'Tue': 2, 'Wed': 3}

Q: what happens if we assign a new value to an existing key?

# Comparison operator

In [28]:
# delete the previous print keyword used to store an integer
del print

# Logical operator

In [29]:
print(1<=2)

True


In [30]:
a = 1
b = 2
print(a == b)

False


In [31]:
print(a < b and a < a)

False


In [32]:
print(a < b or a < a)

True


In [33]:
print(not a < a)

True


Q: what happens if both sides have different data types? what about boolean values?

# Control flow

In [34]:
if a > b:
    print("a > b")
elif a == b:
    print("a == b")
else:
    print("a < b")

a < b


In [35]:
a if a > b else b

2

Q: write a program to map the scores to grades:

90-100 -> A

80-89  -> B

70-79  -> C


# Function

In [36]:
def my_func(x=1):
    return x+1

In [37]:
my_func(2)

3

In [38]:
def my_func2(x=1, y=2):
    return x+y

In [39]:
my_func2(2,3)

5

In [40]:
my_func2(2)

4

In [41]:
my_func2(y=2)

3

Q: write a function to include the previous if-else statement, and add additional checks on the input and output.

# NumPy ndarray

In [42]:
import numpy as np
array_1d = np.array([1,2,3])
array_1d

array([1, 2, 3])

In [43]:
array_2d = np.array([[1,2],[2,3]])
array_2d

array([[1, 2],
       [2, 3]])

In [121]:
array_3d = np.array([array_2d, array_2d])
array_3d

array([[[1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3]]])

Q: creat a 4-dimensional array.

## Common attributes

In [45]:
array_2d.ndim

2

In [46]:
array_2d.shape

(2, 2)

In [47]:
array_2d.size

4

In [48]:
array_2d.dtype

dtype('int64')

Q: explore other attributes.

## Indexing

In [49]:
array_1d[0]

1

In [50]:
array_1d[1:2]

array([2])

In [51]:
array_2d[0,0]

1

In [52]:
array_2d[:,0]

array([1, 2])

Q: how to access the second element at first row of the second entry in the 3d array?

# Common methods

In [53]:
array_1d.mean()

2.0

In [54]:
array_1d.max()

3

In [55]:
array_1d.min()

1

In [56]:
array_1d.std()

0.816496580927726

In [57]:
array_1d.var()

0.6666666666666666

In [58]:
np.mean(array_1d)

2.0

In [59]:
np.max(array_1d)

3

In [60]:
np.min(array_1d)

1

In [61]:
np.std(array_1d)

0.816496580927726

In [62]:
np.var(array_1d)

0.6666666666666666

In [63]:
np.median(array_1d)

2.0

In [64]:
# get the 80th percentile
np.percentile(array_1d, 0.8)

1.016

Q: how to evaluate if any of the above statements return the same result?

## Element-wise operation and broadcasting

In [65]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a + b

array([3, 5, 7])

In [66]:
c = 2
a + c

array([3, 4, 5])

In [67]:
a * c

array([2, 4, 6])

In [68]:
d = np.array([2,3])
a + d

ValueError: ignored

In [69]:
array_2d = np.array([[1,2],[2,3]])
array_2d + d

array([[3, 5],
       [4, 6]])

Q: explore broadcasting in minusing and division operations of different dimensions.

# Pandas Series

In [125]:
import pandas as pd
pd_series = pd.Series([2,3,4])

In [126]:
pd_series.index

RangeIndex(start=0, stop=3, step=1)

In [127]:
pd_series.values

array([2, 3, 4])

In [128]:
pd_series.index = ["idx1", "idx2", "idx3"]

In [129]:
pd_series

idx1    2
idx2    3
idx3    4
dtype: int64

Q: can two indices be the same?

## Access items via indexing

In [130]:
pd_series[0]

2

In [131]:
pd_series["idx1"]

2

## Slicing a series

In [132]:
pd_series[1:3]

idx2    3
idx3    4
dtype: int64

In [133]:
pd_series["idx2":"idx3"]

idx2    3
idx3    4
dtype: int64

Q: how to display a series in reverse order?

# Pandas DataFrame

In [88]:
pd_df = pd.DataFrame({"GOOG":[580,581,582], 
                      "TSLA":[122,121,123]})
pd_df

GOOG  TSLA
0   580   122
1   581   121
2   582   123

In [87]:
display(pd_df)

GOOG  TSLA
0   580   122
1   581   121
2   582   123

Q: how to add a new stock to the dataframe?

## Common attributes

In [89]:
pd_df.columns

Index(['GOOG', 'TSLA'], dtype='object')

In [90]:
pd_df.index

RangeIndex(start=0, stop=3, step=1)

In [91]:
pd_df.shape

(3, 2)

In [92]:
pd_df.size

6

Q: explore other attributes.

## Data processing

In [95]:
pd_df.index = ["2023-01-01", "2023-01-02", "2023-01-03"]
pd_df

GOOG  TSLA
2023-01-01   580   122
2023-01-02   581   121
2023-01-03   582   123

In [94]:
google = pd_df["GOOG"]
google

2023-01-01    580
2023-01-02    581
2023-01-03    582
Name: GOOG, dtype: int64

In [96]:
pd_df2 = pd_df[["TSLA", "GOOG"]]
pd_df2

TSLA  GOOG
2023-01-01   122   580
2023-01-02   121   581
2023-01-03   123   582

In [97]:
pd_df.loc["2023-01-02","GOOG"]

581

In [98]:
pd_df.loc["2023-01-02"]

GOOG    581
TSLA    121
Name: 2023-01-02, dtype: int64

In [101]:
pd_df.loc["2023-01-01":"2023-01-02", "GOOG":"TSLA"]

GOOG  TSLA
2023-01-01   580   122
2023-01-02   581   121

In [102]:
# choose element at second row and second column
pd_df.iloc[1,1]

121

In [106]:
pd_df.iloc[[0,2],[0,1]]

GOOG  TSLA
2023-01-01   580   122
2023-01-03   582   123

In [108]:
pd_df.iloc[0:2,0:2]

GOOG  TSLA
2023-01-01   580   122
2023-01-02   581   121

Q: how to determine which property to use?

## Conditional operations

In [109]:
pd_df > 150

GOOG   TSLA
2023-01-01  True  False
2023-01-02  True  False
2023-01-03  True  False

In [110]:
pd_df['TSLA'] > 150

2023-01-01    False
2023-01-02    False
2023-01-03    False
Name: TSLA, dtype: bool

In [113]:
pd_df.loc[pd_df["GOOG"]>580]

GOOG  TSLA
2023-01-02   581   121
2023-01-03   582   123

In [115]:
pd_df.loc[(pd_df["GOOG"]>580) & (pd_df["TSLA"]>121)]

GOOG  TSLA
2023-01-03   582   123

In [116]:
pd_df.loc[(pd_df["GOOG"]>580) | (pd_df["TSLA"]>121)]

GOOG  TSLA
2023-01-01   580   122
2023-01-02   581   121
2023-01-03   582   123

In [117]:
pd_df.loc[~(pd_df["GOOG"]>580)]

GOOG  TSLA
2023-01-01   580   122

Q: which date has the highest stock price for both stocks?